routes/web.php
<?php

use App\Http\Controllers\JuegosController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('juegos', JuegosController::class)->except([
    'show'
]);

Route::post('juegos/upload-image', [JuegosController::class, 'upload_image'])->name('juegos.upload-image');

app/Models/Juegos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Juegos extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'url',
        'url_image',
        'description',
        'status'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/JuegosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Juegos;
use App\Http\Requests\StoreJuegosRequest;
use App\Http\Requests\UpdateJuegosRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;


class JuegosController extends Controller
{
   
    public function index()
    {
       $juegos = Juegos::paginate(10);
       return view('juegos.index')->with('juegos', $juegos);
     
    }

   
    public function create()
    {
        return view('juegos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreJuegosRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreJuegosRequest $request)
    {
        Juegos::Create([
            'name' => $request->name,
            'url' =>  $request->url,
            'url_image' => $request->url_image,
            'description' => $request->description,
            'status' => $request->status
        ]);
    	
        return redirect()->route('juegos.index')->with('status', 'Juego Creado con éxito');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Juegos  $juegos
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $juego = Juegos::FindOrFail($id);
        return view('juegos.edit')->with('juego', $juego);
    }

    
    public function update(UpdateJuegosRequest $request, $id)
    {
        // dd($request);
        $juego = Juegos::FindOrFail($id);
        $juego->name = $request->name;
        $juego->url =  $request->url;
        $juego->url_image = $request->url_image;    
        $juego->description = $request->description;
        $juego->status = $request->status;

        $juego->save();
        return redirect()->route('juegos.index')->with('status', 'Juego Actualizado con éxito');
    }

    

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Juegos  $juegos
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        Juegos::findOrFail($id)->delete();
        return response()->json(['msg' => 'Juego Eliminado con éxito']);
       
    }

    public function upload_image(Request $request){

        try {
            $imagen_decoded = $request->img;
            
            $ext = $request->ext;
            
            $folderPath = "img/imagenes_juegos/";
            if(!File::exists($folderPath)) {
                File::makeDirectory($folderPath, $mode = 0777, true, true);
            }
        
            $image_parts = explode(";base64,", $imagen_decoded);
            
            $image_base64 = base64_decode($image_parts[1]);
            $file = $folderPath . uniqid() . '.'.$ext;
            if(file_put_contents($file, $image_base64)){
                $ruta_final = asset($file);
                return response()->json(["result" => true, "msg" => "Archivo cargado con éxito", "archivo" => $ruta_final]);  
            }else{
                return response()->json(["result" => false, "msg" => "Ha ocurrido un error, no se ha cargado el archivo"]);  
            }

        } catch (\Throwable $th) {
            
            return response()->json(["result" => false, "msg" => "Ha ocurrido un error, no se ha cargado el archivo", "det" => $th->getMessage()]);  
        }
               
         
        
    }
}

resources/views/juegos/create.blade.php
@extends('layouts.app')
@section('breadcrumb')
<ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{route('juegos.index')}}">Juegos</a></li>
    <li class="active">Crear</li>
</ol>
@endsection
@section('contenido')
<section class="content-header">
    <h1>
        Juegos
    </h1>
</section>
@if ($errors->any())
<script>
    swal("Error al crear juego!", "@php echo implode('\n',$errors->all()) @endphp", "error");

</script>
@endif

<div class="row">
    <div class="col-md-8">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Crear Nuevo Juego</h3>
            </div>
            <form role="form" action="{{route('juegos.store')}}" method="POST">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        <input type="name" class="form-control" id="name" name="name" placeholder="Nombre">
                    </div>

                    <div class="form-group">
                        <label for="url">Url del Juego</label>
                        <input type="url" class="form-control" name="url" id="url" placeholder="Url">
                    </div>
                    <div class="form-group">
                        <label for="description">Descripción</label>
                        <textarea id="description" class="form-control" name="description" rows="10" ></textarea>
                        <div>
                            <div class="form-group">
                                <label for="img_file">Imagen del Juego</label>
                                <span>
                                    <img src="{{asset('img/no_image.jpg')}}" id="img_preview" width="400px" heigth="400px" />
                                </span>
                                <input type="file" id="img_file" name="img_file">
                                <br>
                                <label>Tambien puede ingresar la imagen de forma manual presinando <a id="edit-url-image">aqui</a></label>
                                <input type="text" name="url_image" id="url_image" value="" class="form-control" readonly>

                            </div>

                            <div class="form-group">
                                <label for="status">Estado</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="1">Activo</option>
                                    <option value="0">Inactivo</option>

                                </select>
                            </div>
                        </div>
                      <div class="box-footer">
                          <button type="submit" class="btn btn-primary">Crear Juego</button>
                      </div>
            </form>
        </div>

@endsection

@section('js')
<script src="{{asset('js/Juegos/carga-imagenes.js')}}"></script>
@endsection

resources/views/juegos/edit.blade.php
@extends('layouts.app')
@section('breadcrumb')
<ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{route('juegos.index')}}">Juegos</a></li>
    <li class="active">Editar</li>
</ol>
@endsection
@section('contenido')
<section class="content-header">
    <h1>
        Juegos
    </h1>
</section>
@if ($errors->any())
<script>
    swal("¡Error al editar juego!", "@php echo implode('\n',$errors->all()) @endphp", "error");
</script>
@endif

<div class="row">
    <div class="col-md-8">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Editar Juego</h3>
            </div>
            <form role="form" action="{{route('juegos.update', $juego->id)}}" method="POST">
                @method('put')
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        <input type="name" class="form-control" id="name" name="name" placeholder="Nombre" value="{{$juego->name}}">
                    </div>

                    <div class="form-group">
                        <label for="url">Url del Juego</label>
                        <input type="url" class="form-control" name="url" id="url" placeholder="Url" value="{{$juego->url}}">
                    </div>
                    <div class="form-group">
                        <label for="description">Descripción</label>
                        <textarea id="description" class="form-control" name="description" rows="10" cols="80">{{$juego->description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="img_file">Imagen del Juego</label>
                        <span>
                            <img src="{{($juego->url_image != '') ? $juego->url_image : asset('img/no_image.jpg') }}" id="img_preview" width="400px" heigth="400px" />
                        </span>
                        <input type="file" id="img_file" name="img_file">
                        <br>
                        <label>Tambien puede ingresar la imagen de forma manual presinando <a id="edit-url-image">aqui</a></label>
                        <input type="text" name="url_image" id="url_image" value="{{$juego->url_image}}" class="form-control" readonly>

                    </div>

                    <div class="form-group">
                        <label for="status">Estado</label>
                        <select name="status" id="status" class="form-control">
                            <option value="1" {{($juego->status == '1') ? 'selected' : ''}}>Activo</option>
                            <option value="0" {{($juego->status == '0') ? 'selected' : ''}}>Inactivo</option>
                        </select>
                    </div>
                </div>
              <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Editar Juego</button>
              </div>
            </form>
        </div>

@endsection

@section('js')
<script src="{{asset('js/Juegos/carga-imagenes.js')}}"></script>
@endsection

resources/views/juegos/index.blade.php
@extends('layouts.app')

@section('breadcrumb')
<ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Juegos</a></li>

</ol>
@endsection
@section('contenido')

<section class="content-header">
    <h1>Juegos</h1>
</section>
@if(session('status'))
<script>
    swal("¡Juego Creado!", "{{session('status')}}", "success");

</script>
{{-- <h4>{{session('status')}}</h4> --}}
@endif


<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Listado de Juegos</h3>
                @csrf
                <div class="box-tools">
                    <div class="input-group input-group-sm " style="width: 150px;">
                        <a type="button" href="{{route('juegos.create')}}" class="btn btn-block btn-primary">Crear Nuevo Juego</a>
                    </div>
                </div>
            </div>

            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>#</th>
                        <th>Nombre de Juego</th>
                        <th>Url de juego</th>
                        <th>Imagen</th>
                        <th>Última modificación Registro</th>
                        <th>Estado</th>

                        <th>Opciones</th>
                    </tr>
                    @foreach ($juegos as $j )
                    <tr>
                        <td>{{$loop->iteration }}</td>
                        <td>{{$j->name}}</td>
                        <td><a href="{{$j->url}}" target="_blank">{{$j->url}}</a></td>
                        <td><button class="ver-imagen btn btn-default" data-toggle="modal" data-target="#exampleModal" rel="{{$j->url_image}}">Ver imagen</button></td>
                        <td>{{$j->updated_at->format('d-m-Y H:i:s')}}</td>
                        <td>
                            @if($j->status == 1)
                            <span class="label label-success">Activo</span>
                            @else
                            <span class="label label-danger">Inactivo</span>
                            @endif

                        </td>
                        <td>
                            <span>
                                <a href="{{route('juegos.edit', $j->id)}}"><i class="fa fa-edit"></i>Editar</a>
                            </span>
                            <a rel="{{$j->id}}" class="eliminar" type="button"><i class="fa fa-trash"></i>Eliminar</a>
                        </td>
                    </tr>
                    @endforeach


                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                {{$juegos->onEachSide(5)->links()}}
            </div>
        </div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Imagen de juego</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <img src="asset('img/no_image.jpg')" id="img_preview" width="400px" heigth="400px" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
@endsection
@section('js')
<script>
    $(document).on('click', '.eliminar', function() {
        let id = $(this).attr('rel');
        var token = $('input[name="_token"]').val();

        swal("Eliminar juego", "¿Está seguro de eliminar el juego?", 'warning', {
                buttons: {
                    cancel: "Cancelar"
                    , confirmar: "Confirmar"
                },
              })
            .then((value) => {
                switch (value) {
                    case "cancel":
                        break;

                    case "confirmar":
                        $.ajax({
                            url: '/juegos/' + id,
                              type: 'DELETE',
                              dataType: 'json',
                              data: {
                                id: id
                            },
                              headers: {
                                'X-CSRF-TOKEN': token,
                              },
                              success: function(json) {
                                swal("¡Juego Eliminado!", json.msg, "warning");
                                setTimeout(function() {
                                    window.location.reload();
                                }, 2000);

                            },error: function(j) {
                                swal("¡Ha ocurrido un error!", "Ha ocurrido un error, no se ha eliminado el juego", "error");
                            }
                        });
                        break;
                }
            });
    });
</script>
<script>
$(document).on('click', '.ver-imagen', function(){
  let img = $(this).attr('rel');
  document.getElementById("img_preview").src = img;
})

</script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Prueba - Promarketing</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/adminlte/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('css/adminlte/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('css/adminlte/Ionicons/css/ionicons.min.css')}}">
  <!-- Tema y skin -->
  <link rel="stylesheet" href="{{asset('css/adminlte/AdminLTE.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/adminlte/skin-blue.min.css')}}">
  <!--custom css-->
  @yield('css')


  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

        <!--Sweet Alert-->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  @include('layouts.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('layouts.sidebar')

  <div class="content-wrapper">
    <section class="content-header">
      @yield('breadcrumb')
    
    </section>

    <section class="content container-fluid">
        @yield('contenido')
    </section>
  </div>
    @include('layouts.footer')


<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery  -->
<script src="{{asset('js/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{asset('css/adminlte/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('css/adminlte/adminlte.min.js')}}"></script>
<!--Custom js-->
@yield('js')

</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
  Desarrollado por <strong>Víctor Cea Paredes</strong> para la prueba técnica de <b>ProMarketing</b>. Todos los derechos Reservados.
</footer>

resources/views/layouts/header.blade.php
<header class="main-header">
    <a href="index2.html" class="logo">
      <span class="logo-mini"><b>PRO</b></span>
      <span class="logo-lg"><b>ProMarketing</b></span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        </ul>
      </div>
    </nav>
  </header>

resources/views/layouts/sidebar.blade.php
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left info">
          <p></p>
          <a href="#"><i class="fa fa-circle text-success"></i> </a>
        </div>
      </div>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Contenidos</li>
        <li class="active"><a href="{{route('juegos.index')}}"><i class="fa fa-link"></i> <span>Juegos</span></a></li>
      </ul>
    </section>
   
  </aside>